stages:
  - test
  - integration
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

lint:
  image: pipelinecomponents/flake8
  stage: test
  tags:
    - thorchain
  script:
    - flake8

unit-tests:
  image: docker/compose:alpine-1.25.4
  stage: test
  tags:
    - thorchain
  services:
    - docker:19-dind
  before_script:
    - apk update
    - apk add git make
    - make build
  script:
    - RUNE=THOR.RUNE make test-coverage
    - RUNE=THOR.RUNE make test-coverage-report

integration:
  image: docker/compose:alpine-1.25.4
  stage: integration
  tags:
    - thorchain
  services:
    - docker:19-dind
  variables:
  artifacts:
    when: on_failure
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./logs/
  before_script:
    - apk update
    - apk add git make
    - (git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/midgard-v2.git && cd midgard-v2 && docker build -t registry.gitlab.com/thorchain/midgard:develop . && cd ..) || true
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/thornode.git || git clone --single-branch -b master https://gitlab.com/thorchain/thornode.git
    - cd thornode
    - test master = $(git rev-parse --abbrev-ref HEAD) && docker pull registry.gitlab.com/thorchain/thornode:mocknet
    - NATIVE=true make -C build/docker reset-mocknet-standalone
    - cd ..
  script:
    - make build
    - RUNE=THOR.RUNE make smoke
  after_script:
    - ./thornode/scripts/docker_logs.sh


# Build docker image
build-thornode:
  stage: build
  image: docker:stable
  tags:
    - thorchain
  only:
    - master
  services:
    - docker:19-dind
  before_script:
    - apk update
    - apk add py-pip make git jq curl
    - make docker-gitlab-login
  script:
    - make docker-gitlab-build
    - make docker-gitlab-push
