apiVersion: batch/v1
kind: Job
metadata:
  name: smoke-tests
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: heimdall
        image: registry.gitlab.com/thorchain/heimdall
        imagePullPolicy: Always
        volumeMounts:
          - name: app
            mountPath: /app
        env:
          - name: LOGLEVEL
            value: INFO
        command:
          - python
          - scripts/smoke.py
          - --fast-fail=True
          - --thorchain=http://thor-api:1317
          - --binance=http://binance-daemon:26660
          - --ethereum=http://ethereum-daemon:8545
          - --bitcoin=http://thorchain:password@bitcoin-daemon:18443
          - --thorchain-websocket=ws://thor-daemon:26657/websocket
          - --midgard=http://midgard
      restartPolicy: Never
      volumes:
        - name: app
          hostPath:
            path: /root/heimdall
